### ISSUE TITLE
H-JS or H-Min divergence ?

### ISSUE THREAD

**Issue by perone** [a7b23/H-Divergence#1]
Hi, thanks for sharing the code. I was reading the code and it seems that the [agriculture example](https://github.com/a7b23/H-Divergence/blob/main/climate_exps/vdiv_agriculture.py#L292) you are using a H-Min divergence instead of the H-JS divergence mentioned in the paper for this particular example. Is the code different than the one used in the paper or was it a typo in the paper ? Thank you !

**Comment by a7b23** [comment]
Hi, thanks for pointing this out. I believe I had used H-JS divergence only, but during the publishing of the code I used H-min divergence.

**Comment by a7b23** [comment]
Please feel free to re-open this issue, in case you face any further issue!

**Comment by perone** [comment]
Thank you @a7b23 !
