### ISSUE TITLE
Regarding threshold computation

### ISSUE THREAD

**Issue by Piyushi-0** [a7b23/H-Divergence#3]
Hi, 
Thank you for sharing the code.
I have a query regarding threshold computation, for e.g. in line 166 of [utils.py](https://github.com/a7b23/H-Divergence/blob/main/utils.py).
Shouldn't `S_jsv_vector[np.int(np.ceil(N_per * (1 - alpha)))]` instead be `S_jsv_vector[int(N_per * (1 - alpha))]`? 
Especially when `N_per `is small (say 3), `ceil(N_per * (1 - alpha))` can be equal to `N_per` with the default `alpha`, causing indexing error.
Please let me know if I am missing something.

Regards,
Piyushi

**Comment by KellyYutongHe** [comment]
Thanks for raising this question! First of all I would like to emphasize that we used N_per = 100 for all our experiments so ceiling and flooring doesn't makes a difference in our experiments.
Now regarding your question, I think if you do flooring, then the threshold would be lower than what it is supposed to. Plus we usually pick a large number of permutations for the test to be valid. Lastly, this is consistent with our baselines: https://github.com/fengliu90/DK-for-TST/blob/master/utils.py .
Thanks!
