### ISSUE TITLE
Regarding fixed seed for each trial

### ISSUE THREAD

**Issue by Piyushi-0** [a7b23/H-Divergence#4]
For sampling `s1`, `s2` in the blobs experiments, the same seed is being used `np.random.seed(seed=11 * k + 10 + n)` in each trial. Ref. https://github.com/a7b23/H-Divergence/blob/19030d37b1cd3f115db036ad2bd5d53ee89255ae/blob_gmm.py#L105 and https://github.com/a7b23/H-Divergence/blob/19030d37b1cd3f115db036ad2bd5d53ee89255ae/blob_kde.py#L137 It doesn't depend on the variable `kk` denoting the trial index. Could you please share the reason for this?

**Comment by KellyYutongHe** [comment]
We followed the experiment setup from Liu, et. al 2020 (https://github.com/fengliu90/DK-for-TST/blob/master/Baselines_Blob.py) and this is how they set the random seed.
